# Generated by Django 3.2.16 on 2023-01-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('authentication', '0001_initial'),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_result', models.FloatField()),
                ('term', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=50)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gradeLEVEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.grades')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('empprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hr.empprofile')),
                ('teached_classRooms', models.ManyToManyField(blank=True, to='admission.ClassRoom')),
                ('teached_subjects', models.ManyToManyField(blank=True, to='admission.Subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.teacher')),
            ],
            bases=('hr.empprofile',),
        ),
        migrations.AddField(
            model_name='subjscore',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.subject'),
        ),
        migrations.AddField(
            model_name='subjevalutyp',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='gradeLEVEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.grades'),
        ),
        migrations.AddField(
            model_name='studentterm',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.termsofgrade'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.classroom'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gradeLEVEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.grades'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.guardianprofile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.student'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.studentprofile'),
        ),
        migrations.AddField(
            model_name='result',
            name='subjEvalu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.evaluation'),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.studentprofile'),
        ),
        migrations.AddField(
            model_name='finepaymant',
            name='fine_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.fineinvoice'),
        ),
        migrations.AddField(
            model_name='fineinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.studentprofile'),
        ),
        migrations.AddField(
            model_name='feepaymant',
            name='fee_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.feeinvoice'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='payment_Plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.paymentplan'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='services',
            field=models.ManyToManyField(blank=True, to='admission.Services'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.studentprofile'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluTyp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.subjevalutyp'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.subject'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='gradeLEVEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.grades'),
        ),
    ]
