# Generated by Django 3.2.16 on 2023-02-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='emp_type',
            field=models.CharField(default='teacher', max_length=50),
        ),
    ]
