# Generated by Django 3.2.16 on 2023-01-27 15:35

import birthday.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_name', models.CharField(max_length=50)),
                ('descraption', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('emp_id', models.IntegerField(blank=True, null=True)),
                ('id_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=400)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('birth_date', birthday.fields.BirthdayField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('joining_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('emp_status', models.CharField(max_length=70)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.departments')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.empprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeavesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_name', models.CharField(max_length=50)),
                ('descraption', models.CharField(max_length=500)),
                ('num_of_days', models.IntegerField()),
                ('for_all_genders', models.BooleanField(default=True)),
                ('tot_allowed_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_req_id', models.CharField(blank=True, max_length=15, null=True)),
                ('days_name', models.CharField(max_length=50)),
                ('descraption', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_of_days', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('DENIED', 'denied')], default='pending', max_length=35)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.empprofile')),
                ('leaveType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavestype')),
            ],
        ),
        migrations.CreateModel(
            name='EmpLeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_days_left', models.IntegerField()),
                ('emp', models.ManyToManyField(to='hr.EmpProfile')),
                ('leaveTyp', models.ManyToManyField(to='hr.LeavesType')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('empprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hr.empprofile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.staff')),
            ],
            bases=('hr.empprofile',),
        ),
    ]
